//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 11:44:04 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:bes-external-call.informatica.mdm")
package com.webserviceSoapbe.pojos2;
