//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.01 at 06:35:49 PM EDT 
//


package com.springsoapBe.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * External Web Service should accept this type as request (message part for soap operation input)
 * 
 * <p>Java class for ExternalCallRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalCallRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{urn:bes-external-call.informatica.mdm}Header"/&gt;
 *         &lt;element name="trigger" type="{urn:bes-external-call.informatica.mdm}Trigger"/&gt;
 *         &lt;element name="serviceCall" type="{urn:bes-external-call.informatica.mdm}ServiceCall"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalCallRequest", propOrder = {
    "header",
    "trigger",
    "serviceCall"
})
public class ExternalCallRequest {

    @XmlElement(required = true)
    protected Header header;
    @XmlElement(required = true)
    protected Trigger trigger;
    @XmlElement(required = true)
    protected ServiceCall serviceCall;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link Trigger }
     *     
     */
    public Trigger getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trigger }
     *     
     */
    public void setTrigger(Trigger value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the serviceCall property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCall }
     *     
     */
    public ServiceCall getServiceCall() {
        return serviceCall;
    }

    /**
     * Sets the value of the serviceCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCall }
     *     
     */
    public void setServiceCall(ServiceCall value) {
        this.serviceCall = value;
    }

}
