//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.01 at 06:35:49 PM EDT 
//


package com.springsoapBe.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Explains context for external web service call: Business Entity that is being processed by Hub, processing phase.
 * 
 * <p>Java class for Trigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trigger"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="businessEntity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="servicePhase" type="{urn:bes-external-call.informatica.mdm}ServicePhase"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trigger", propOrder = {
    "businessEntity",
    "servicePhase"
})
public class Trigger {

    @XmlElement(required = true)
    protected String businessEntity;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ServicePhase servicePhase;

    /**
     * Gets the value of the businessEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntity() {
        return businessEntity;
    }

    /**
     * Sets the value of the businessEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntity(String value) {
        this.businessEntity = value;
    }

    /**
     * Gets the value of the servicePhase property.
     * 
     * @return
     *     possible object is
     *     {@link ServicePhase }
     *     
     */
    public ServicePhase getServicePhase() {
        return servicePhase;
    }

    /**
     * Sets the value of the servicePhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicePhase }
     *     
     */
    public void setServicePhase(ServicePhase value) {
        this.servicePhase = value;
    }

}
