//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.02 at 03:15:15 PM EDT 
//


package com.test.example2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * External Web Service should return this type as request (message part for soap operation output)
 * 
 * <p>Java class for ExternalCallResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalCallResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="serviceCall" type="{urn:bes-external-call.informatica.mdm}ServiceCall"/>
 *         &lt;element name="serviceError" type="{urn:bes-external-call.informatica.mdm}ServiceError"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalCallResponse", propOrder = {
    "serviceCall",
    "serviceError"
})
public class ExternalCallResponse {

    protected ServiceCall serviceCall;
    protected ServiceError serviceError;

    /**
     * Gets the value of the serviceCall property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCall }
     *     
     */
    public ServiceCall getServiceCall() {
        return serviceCall;
    }

    /**
     * Sets the value of the serviceCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCall }
     *     
     */
    public void setServiceCall(ServiceCall value) {
        this.serviceCall = value;
    }

    /**
     * Gets the value of the serviceError property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceError }
     *     
     */
    public ServiceError getServiceError() {
        return serviceError;
    }

    /**
     * Sets the value of the serviceError property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceError }
     *     
     */
    public void setServiceError(ServiceError value) {
        this.serviceError = value;
    }

}
