//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.01 at 01:55:47 PM EDT 
//


package com.webserviceSoapbe.pojos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerRequest" type="{urn:bes-external-call.informatica.mdm}ExternalCallRequest"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerRequest"
})
@XmlRootElement(name = "CustomerRequest")
public class CustomerRequest {

    @XmlElement(name = "CustomerRequest", required = true)
    protected ExternalCallRequest customerRequest;

    /**
     * Gets the value of the customerRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalCallRequest }
     *     
     */
    public ExternalCallRequest getCustomerRequest() {
        return customerRequest;
    }

    /**
     * Sets the value of the customerRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalCallRequest }
     *     
     */
    public void setCustomerRequest(ExternalCallRequest value) {
        this.customerRequest = value;
    }

}
