//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 01:24:59 PM EDT 
//


package com.webserviceSoap.pojos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webserviceSoap.pojos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Validate_QNAME = new QName("http://cs.sample.mdm.informatica.com/", "validate");
    private final static QName _ValidateResponse_QNAME = new QName("http://cs.sample.mdm.informatica.com/", "validateResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webserviceSoap.pojos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalCallRequest }
     * 
     */
    public ExternalCallRequest createExternalCallRequest() {
        return new ExternalCallRequest();
    }

    /**
     * Create an instance of {@link ExternalCallResponse }
     * 
     */
    public ExternalCallResponse createExternalCallResponse() {
        return new ExternalCallResponse();
    }

    /**
     * Create an instance of {@link Password }
     * 
     */
    public Password createPassword() {
        return new Password();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Trigger }
     * 
     */
    public Trigger createTrigger() {
        return new Trigger();
    }

    /**
     * Create an instance of {@link ServiceCall }
     * 
     */
    public ServiceCall createServiceCall() {
        return new ServiceCall();
    }

    /**
     * Create an instance of {@link ServiceError }
     * 
     */
    public ServiceError createServiceError() {
        return new ServiceError();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link CustomerRequest }
     * 
     */
    public CustomerRequest createCustomerRequest() {
        return new CustomerRequest();
    }

    /**
     * Create an instance of {@link Acknowledgement }
     * 
     */
    public Acknowledgement createAcknowledgement() {
        return new Acknowledgement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalCallRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExternalCallRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://cs.sample.mdm.informatica.com/", name = "validate")
    public JAXBElement<ExternalCallRequest> createValidate(ExternalCallRequest value) {
        return new JAXBElement<ExternalCallRequest>(_Validate_QNAME, ExternalCallRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalCallResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExternalCallResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://cs.sample.mdm.informatica.com/", name = "validateResponse")
    public JAXBElement<ExternalCallResponse> createValidateResponse(ExternalCallResponse value) {
        return new JAXBElement<ExternalCallResponse>(_ValidateResponse_QNAME, ExternalCallResponse.class, null, value);
    }

}
