//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.02 at 03:38:18 PM EDT 
//


package com.test.example6;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test.example6 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://www.pfgpartyentity.com/Employee", "Request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test.example6
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalCallRequest }
     * 
     */
    public ExternalCallRequest createExternalCallRequest() {
        return new ExternalCallRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalCallRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.pfgpartyentity.com/Employee", name = "Request")
    public JAXBElement<ExternalCallRequest> createRequest(ExternalCallRequest value) {
        return new JAXBElement<ExternalCallRequest>(_Request_QNAME, ExternalCallRequest.class, null, value);
    }

}
